# Pandas 고급 필터링과 정렬

## 📚 용어 정리 (Terminology)

### 필터링 관련 용어

| 용어 (한글) | 용어 (영문) | 정의 | 예시 |
|------------|-----------|------|------|
| **필터링** | Filtering | 조건에 맞는 데이터만 선택하는 것 | `df[df['Age'] > 20]` |
| **복합 조건** | Compound Condition | 두 개 이상의 조건을 결합 | `(조건1) & (조건2)` |
| **마스크** | Mask | True/False 값의 배열 | `[True, False, True]` |
| **쿼리** | Query | 데이터를 질의(검색)하는 것 | SQL의 SELECT와 유사 |

### 정렬 관련 용어

| 용어 (한글) | 용어 (영문) | 정의 | 예시 |
|------------|-----------|------|------|
| **정렬** | Sort | 데이터를 특정 순서로 배열 | 오름차순, 내림차순 |
| **오름차순** | Ascending | 작은 값 → 큰 값 순서 | 1, 2, 3, 4, 5 |
| **내림차순** | Descending | 큰 값 → 작은 값 순서 | 5, 4, 3, 2, 1 |
| **정렬 기준** | Sort Key | 정렬할 때 기준이 되는 컬럼 | `by='Age'` |
| **결측치 정렬 위치** | NA Position | NaN 값을 정렬에서 어디에 둘지 | `first` 또는 `last` |

### 파일 입출력 용어

| 용어 (한글) | 용어 (영문) | 정의 | 확장자 |
|------------|-----------|------|--------|
| **CSV** | Comma Separated Values | 쉼표로 구분된 텍스트 파일 | `.csv` |
| **TSV** | Tab Separated Values | 탭으로 구분된 텍스트 파일 | `.tsv` |
| **인코딩** | Encoding | 문자를 컴퓨터가 이해하는 코드로 변환 | UTF-8, EUC-KR |
| **구분자** | Delimiter | 데이터를 구분하는 문자 | `,` (쉼표), `	` (탭) |
| **헤더** | Header | 파일의 첫 줄 (컬럼명이 있는 줄) | Column names |

### 문자열 메서드 용어

| 용어 (한글) | 용어 (영문) | 정의 | 예시 |
|------------|-----------|------|------|
| **시작 문자열** | startswith | 특정 문자열로 시작하는지 검사 | `'ABC'.startswith('A')` → True |
| **끝 문자열** | endswith | 특정 문자열로 끝나는지 검사 | `'ABC'.endswith('C')` → True |
| **포함** | contains | 특정 문자열을 포함하는지 검사 | `'ABC'.contains('B')` → True |
| **접두사** | Prefix | 문자열의 시작 부분 | 'Pre'fix |
| **접미사** | Suffix | 문자열의 끝 부분 | Suf'fix' |

---

## 1. 복합 조건 필터링

여러 개의 조건을 조합하여 데이터를 필터링할 수 있습니다.

### 조건 연산자
| 연산자 | 설명 | 예시 |
|--------|------|------|
| `&` | AND (그리고) | `(조건1) & (조건2)` |
| `\|` | OR (또는) | `(조건1) \| (조건2)` |
| `~` | NOT (부정) | `~(조건)` |

### 주의사항
- 각 조건은 반드시 **괄호 ()** 로 묶어야 함
- `and`, `or` 대신 `&`, `|` 사용 (비트 연산자)
- 문자열 메서드: `.str.startswith()`, `.str.contains()`, `.str.endswith()` 등

In [26]:
# 샘플 데이터 생성
import pandas as pd

df = pd.DataFrame({'Name': ['RACHEL', 'MONICA', 'PHOEBE',
                                   'ROSS', 'CHANDLER', 'JOEY'],
                          'Age': [30, 35, 37, 33, 34, 30],
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

df

       Name  Age  Salary          JOB
0    RACHEL   30  100000     DESIGNER
1    MONICA   35   93000         CHEF
2    PHOEBE   37   88000        MASUS
3      ROSS   33  120000  PALENTOLOGY
4  CHANDLER   34   94000           IT
5      JOEY   30   95000       ARTIST

In [ ]:
# 복합 조건 필터링 예시
# 조건 1: Salary >= 100000 (연봉 10만 이상)
# 조건 2: Age < 40 (40세 미만)
# 조건 3: JOB이 'D'로 시작 (JOB 컬럼의 값이 D로 시작)
# & (AND) 연산으로 세 조건을 모두 만족하는 행 선택
# 마지막에 ['Name', 'JOB']으로 원하는 컬럼만 선택

df.loc[(df['Salary']>=100000) & (df['Age']< 40) & (df['JOB'].str.startswith('D')), ['Name','JOB']]

     Name       JOB
0  RACHEL  DESIGNER

## 2. 데이터 정렬 (Sorting)

### 📚 정렬 용어 상세 정리

```
오름차순 (Ascending) vs 내림차순 (Descending)

오름차순:  1 → 2 → 3 → 4 → 5  (작은 값에서 큰 값으로)
            ↑              ↑
          시작           끝

내림차순:  5 → 4 → 3 → 2 → 1  (큰 값에서 작은 값으로)
            ↑              ↑
          시작           끝
```

### 정렬 방향 비교

| 구분 | 숫자 | 문자열 | 날짜 |
|------|------|--------|------|
| **오름차순** | 1, 2, 3... | A, B, C... (가나다순) | 과거 → 미래 |
| **내림차순** | 3, 2, 1... | Z, Y, X... (하파타순) | 미래 → 과거 |

### 정렬 관련 파라미터 상세 설명

| 파라미터 | 의미 | 기본값 | 설명 |
|----------|------|--------|------|
| `by` | 기준 (기준) | 필수 | 어떤 컬럼을 기준으로 정렬할지 |
| `ascending` | 오름차순 (상승하는) | True | True=오름차순, False=내림차순 |
| `ignore_index` | 인덱스 무시 | False | True면 정렬 후 인덱스를 0부터 재설정 |
| `inplace` | 제자리에서 | False | True면 원본 DataFrame 직접 수정 |
| `na_position` | NA 위치 | 'last' | 결측치를 'first' 또는 'last'로 배치 |
| `kind` | 종류 | 'quicksort' | 정렬 알고리즘 (quicksort, mergesort, heapsort) |

### inplace 파라미터 중요!

```python
# inplace=False (기본값): 원본은 변경되지 않고 새로운 DataFrame 반환
df_sorted = df.sort_values(by='Age')  # df는 그대로, 새로운 객체 반환

# inplace=True: 원본 DataFrame을 직접 수정하고 아무것도 반환하지 않음
df.sort_values(by='Age', inplace=True)  # df 자체가 변경됨
```

### sort_values(): 값 기준 정렬

```python
df.sort_values(by='컬럼명')           # 오름차순 정렬
df.sort_values(by='컬럼명', ascending=False)  # 내림차순 정렬
df.sort_values(by=['컬럼1', '컬럼2'])  # 다중 컬럼 정렬
```

### 주요 파라미터
| 파라미터 | 설명 | 기본값 |
|----------|------|--------|
| `by` | 정렬 기준 컬럼 | 필수 |
| `ascending` | 오름차순 여부 | True |
| `ignore_index` | 인덱스 재설정 | False |
| `inplace` | 원본 수정 여부 | False |
| `na_position` | 결측치 위치 | 'last' |

In [4]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [5]:
# Age 컬럼을 기준으로 오름차순 정렬 (ascending=True가 기본값)
# 나이가 적은 사람부터 많은 사람 순서로 정렬

sorted_df = df.sort_values(by='Age')
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [6]:
# Age 컬럼을 기준으로 내림차순 정렬 (ascending=False)
# 나이가 많은 사람부터 적은 사람 순서로 정렬

sorted_df = df.sort_values(by='Age',ascending=False)
print(sorted_df)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [7]:
# ignore_index=True: 정렬 후 인덱스를 0부터 다시 부여
# 정렬 전의 원래 인덱스가 아닌, 새로운 순차적 인덱스가 생성됨

sorted_df = df.sort_values(by='Age',ascending=False, ignore_index=True)
print(sorted_df)

      Name  Age  Score
0    David   40     80
1  Charlie   35     95
2      Bob   30     90
3    Alice   25     85

In [ ]:
# inplace=True

In [8]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [10]:
# 'Age' 값이 같은 경우, 'Score'로 sorting
sorted_df = df.sort_values(by=['Age', 'Score'])
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [11]:
import pandas as pd
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)
df_nan

      Name   Age
0    Alice  28.0
1      Bob  22.0
2  Charlie   NaN
3    David  22.0

In [ ]:
# default: 결측치는 마지막으로

# sorted_df = df_nan.sort_values(by="Age", na_position="first")
sorted_df = df_nan.sort_values(by="Age")
print(sorted_df)

      Name   Age
1      Bob  22.0
3    David  22.0
0    Alice  28.0
2  Charlie   NaN

In [ ]:
# 인덱스 정렬

In [14]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [ ]:
# default는 ascending 순서
df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [16]:
df_sorted_by_index_desc = df.sort_index(ascending=False)
print(df_sorted_by_index_desc)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

## 3. CSV 파일 읽기 (read_csv)

### 📚 파일 입출력 용어 상세 정리

#### CSV 파일 구조 이해하기

```
CSV (Comma Separated Values) 파일의 낶부 구조:

헤더 행 →   Name,Age,City
           ↓  ↓   ↓   ← 쉼표(Comma)로 구분
데이터 행 → Alice,25,Seoul
          Bob,30,Busan
          Charlie,35,Incheon
           ↑   ↑    ↑
        각 셀(Cell)의 값
```

#### 파일 형식별 특징

| 형식 | 이름 | 구분자 | 특징 | 사용 예 |
|------|------|--------|------|---------|
| **CSV** | Comma Separated Values | 쉼표 `,` | 가장 일반적 | Excel 데이터 교환 |
| **TSV** | Tab Separated Values | 탭 `	` | 쉼표가 들어간 데이터에 유용 | 생물정보학 데이터 |
| **JSON** | JavaScript Object Notation | 중괄호 `{}` | 계층적 데이터 | API 응답 데이터 |
| **Excel** | Excel File | 바이너리 | 여러 시트 지원 | `.xlsx`, `.xls` |

#### 인코딩 (Encoding) 이해하기

| 인코딩 | 설명 | 사용 상황 |
|--------|------|-----------|
| **UTF-8** | 유니코드 표준 | 전 세계 표준, 한글/영문 모두 지원 |
| **CP949** | 한국어 Windows 기본 | Windows에서 생성된 한글 파일 |
| **EUC-KR** | 한국어 표준 | 오래된 한국어 시스템 |
| **ASCII** | 영문 기본 | 영어만 있는 경우 |

```python
# 한글이 깨질 때 인코딩 변경
df = pd.read_csv('data.csv', encoding='utf-8')  # 기본 시도
df = pd.read_csv('data.csv', encoding='cp949')  # Windows 한글 파일
df = pd.read_csv('data.csv', encoding='euc-kr')  # 오래된 한글 파일
```

#### read_csv 주요 파라미터 상세 설명

| 파라미터 | 의미 | 예시 | 설명 |
|----------|------|------|------|
| `filepath` | 파일 경로 | `'data.csv'` | 읽을 파일의 위치 |
| `sep` / `delimiter` | 구분자 | `','` 또는 `'	'` | 데이터 구분 문자 |
| `header` | 헤더 행 | `0` (기본값) | 어떤 행을 컬럼명으로 사용할지 |
| `names` | 컬럼명 지정 | `['A', 'B', 'C']` | 직접 컬럼명 지정 (header=None일 때 사용) |
| `index_col` | 인덱스 컬럼 | `'id'` | 해당 컬럼을 인덱스로 설정 |
| `usecols` | 사용할 컬럼 | `['Name', 'Age']` | 특정 컬럼만 읽기 |
| `dtype` | 데이터 타입 | `{'Age': int}` | 컬럼별 데이터 타입 지정 |
| `nrows` | 읽을 행 수 | `100` | 처음 n행만 읽기 |
| `skiprows` | 건달 행 | `[0, 2]` 또는 `3` | 해당 행을 건달하고 읽기 |
| `na_values` | 결측치 값 | `['N/A', 'NULL']` | 이 값들을 NaN으로 처리 |
| `encoding` | 인코딩 | `'utf-8'` | 파일 인코딩 지정 |
| `skip_blank_lines` | 빈 줄 건달 | `True` | 빈 줄을 건달할지 여부 |

### 기본 문법
```python
df = pd.read_csv('파일경로.csv')
```

### 주요 파라미터
| 파라미터 | 설명 | 예시 |
|----------|------|------|
| `usecols` | 특정 컬럼만 읽기 | `usecols=['Name', 'Age']` |
| `index_col` | 인덱스로 사용할 컬럼 | `index_col='Name'` |
| `nrows` | 읽을 행 수 제한 | `nrows=100` |
| `skiprows` | 건달 행 지정 | `skiprows=[0, 2]` |
| `na_values` | 결측치로 처리할 값 | `na_values=['N/A', 'Unknown']` |
| `encoding` | 파일 인코딩 | `encoding='utf-8'` |

In [ ]:
# CSV 파일을 dataframe으로 읽어오기

In [18]:
# CSV 파일을 기본 설정으로 읽기
# 첫 번째 행이 자동으로 컬럼명으로 인식됨

df = pd.read_csv("people_data.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [19]:
# usecols 파라미터: 필요한 컬럼만 선택적으로 읽기
# 메모리 효율적 사용과 불필요한 데이터 로딩 방지에 유용

df = pd.read_csv("people_data.csv", usecols=["First Name", "Email"])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

In [20]:
# index_col 파라미터: 특정 컬럼을 DataFrame의 인덱스로 설정
# 데이터를 읽을 때 바로 인덱스를 지정할 수 있음

df = pd.read_csv("people_data.csv", index_col="First Name")
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name
Shelby       Terrell    Male        elijah57@example.net    1945-10-26
Phillip      Summers  Female       bethany14@example.com    1910-03-24
Kristine      Travis    Male       bthompson@example.com    1992-07-02
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01

                     Job Title
First Name
Shelby         Games developer
Phillip         Phytotherapist
Kristine             Homeopath
Yesenia      Market researcher
Lori        Veterinary surgeon

In [21]:
# 이런 값이 있으면 NaN으로 바꾸어라 → 결측치 처리

df = pd.read_csv("people_data.csv", na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [23]:
# 몇 라인만 불러오기

df = pd.read_csv('people_data.csv', nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

In [24]:
# 첫 몇 라인은 건너뛰기

df = pd.read_csv("people_data.csv", skiprows = [4,5])
print("Dataset After skipping rows: ")
df

Dataset After skipping rows:

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath