In [41]:

import pandas as pd 
import numpy as np

In [42]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [43]:
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [44]:
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [45]:
# 비효율적인 방법

pop[[i for i in pop.index if i[1]==2000]]

(California, 2000)    33871648
(New York, 2000)      18976457
(Texas, 2000)         20851820
dtype: int64

In [46]:
# list comprehension

# 1. 기존 리스트의 모든 요소에 특정 연산을 적용하여 새 리스트를 만드는 경우
squares = [x**2 for x in range(10)]
print(squares)

words = ['python', 'is', 'awesome']
upper_words = [w.upper() for w in words]
print(upper_words)

# 2. 조건에 맞는 요소만 골라내고 나머지는 버림
evens = [x for x in range(1, 21) if x % 2 == 0]
print(evens)

fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']
a_fruits = [f for f in fruits if 'a' in f]
print(a_fruits)

# 3. 조건에 의해서 새로운 리스트 만들기
numbers = [1, 2, 3, 4, 5]
labels = ['Even' if x % 2 == 0 else 'Odd' for x in numbers]
print(labels)

# 4. for안에 또 다른 for
matrix = [[1, 2], [3, 4], [5, 6]]
flat = [num for row in matrix for num in row]

print(flat)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['PYTHON', 'IS', 'AWESOME']
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
['apple', 'banana', 'mango']
['Odd', 'Even', 'Odd', 'Even', 'Odd']
[1, 2, 3, 4, 5, 6]

In [47]:
matrix = [[1, 2], [3, 4], [5, 6]]

for row in matrix:
    for num in row:
        print(num)

# 두 for를 한 줄에 쓰면
# for row in matrix for num in row

# 마지막 num을 앞쪽에
# num for row in matrix for num in row

1
2
3
4
5
6

In [48]:
# 5. dictionary comprehension

square_dict = {x: x**2 for x in range(5)}
print(square_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [49]:
# pandas MultiIndex

In [52]:
print(index)

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]

In [53]:
print(type(index))

<class 'list'>

In [54]:
index_multi = pd.MultiIndex.from_tuples(index)
index_multi

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [55]:
# 1. pd.MultiIndex.from_product

# 별도의 리스트
states = ['California', 'New York', 'Texas']
years = [2000, 2010]

index_multi = pd.MultiIndex.from_product([states, years], names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [56]:
# 리스트의 리스트

arrays = [
    ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    [2000, 2010, 2000, 2010, 2000, 2010]
]

index_multi = pd.MultiIndex.from_arrays(arrays, names=['state', 'year'])
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [57]:
# 데이터프레임의 컬럼을 사용

df_info = pd.DataFrame({
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010]
})

index_multi = pd.MultiIndex.from_frame(df_info)
print(index_multi)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [58]:
# set_index 사용

data = {
    'state': ['California', 'California', 'New York', 'New York', 'Texas', 'Texas'],
    'year': [2000, 2010, 2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 18.9, 19.3, 20.8, 25.1]
}
df = pd.DataFrame(data)

df_multi = df.set_index(['state', 'year'])

print(df_multi)

                  pop
state      year
California 2000  33.8
           2010  37.2
New York   2000  18.9
           2010  19.3
Texas      2000  20.8
           2010  25.1

In [59]:
# 현재 pop
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [60]:
pop_multi = pop.reindex(index_multi)
pop_multi

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [61]:
type(pop_multi)
# pop_multi의 타입은 Series

pandas.core.series.Series

In [62]:
# 비효율적인 방법
# pop[[i for i in pop.index if i[1]==2000]]

pop_multi[:, 2000]
# pop_multi의 타입은 Series이기 때문에 컬럼이 하나밖에 없음
# pandas는 pop_multi[:, 2000]을 보고 멀티인덱스라고 판단

# pop_multi가 데이터프레임인 경우 pop_multi[:, 2000]는 에러 발생
# df[행, 열]은 없음, df.loc[], df.iloc[]를 사용해야 함

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [68]:
# 정리

import pandas as pd

data = {
    'state': ['California', 'New York', 'Texas', 'Florida'],
    'year': [2000, 2010, 2000, 2010],
    'pop': [33.8, 37.2, 20.8, 18.8]
}
df = pd.DataFrame(data)
df

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2
2       Texas  2000  20.8
3     Florida  2010  18.8

In [69]:
# 1. df[]는 기본적으로 컬럼 선택 → 컬럼 타입은 대체로 문자열

col_state = df['state']
print(col_state)

# 리스트를 넣어서 여러 컬럼 선택
cols = df[['state', 'pop']]
print(cols)

0    California
1      New York
2         Texas
3       Florida
Name: state, dtype: object
        state   pop
0  California  33.8
1    New York  37.2
2       Texas  20.8
3     Florida  18.8

In [70]:
# 2. df[]에 :를 사용하면 행 선택

rows = df[0:2]
print(rows)

# df[]에 쉼표가 없다
# 1. 슬라이스 → 행 선택
# 2.   컬럼명 → 열 선택, [컬럼1, 컬럼 2, ...]은 쉼표가 아니라 단일 리스트를 넘긴 것

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [71]:
# 3. 불리언 마스크를 사용하면 행 선택

mask = df['pop'] > 30
print(df[mask])

        state  year   pop
0  California  2000  33.8
1    New York  2010  37.2

In [72]:
# 컬럼 이름을 알려주지 않음

df = pd.DataFrame([[10, 20], [30, 40]])
# pandas가 디폴트 컬럼 이름 0, 1, 2, ...을 사용
# 이 경우 컬럼명은 숫자 타입에 해당
print(df)
print('-'*100)
print(df[0]) 

# print(df['0']) # KeyError: '0'

    0   1
0  10  20
1  30  40
----------------------------------------------------------------------------------------------------
0    10
1    30
Name: 0, dtype: int64

In [74]:
# pd.Series를 데이터프레임에 끼워넣기

pop_multi

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [75]:
pop_df = pd.DataFrame({
    'total': pop_multi,
    'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014],
})

pop_df

                    total  under18
state      year
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [ ]:
# 인덱스 이름 - 다 만들고 나중에 이름 붙이기

rng = np.random.RandomState(42)

# rng.rand(6, 3)는 난수 생성기(rng)를 사용해서 6행 3열의 2차원 배열을 생성
df = pd.DataFrame(rng.rand(6, 3), 
                  index=[['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]],
                  columns= ['col1', 'col2', 'col3']
                  )

df

         col1      col2      col3
A 1  0.374540  0.950714  0.731994
  2  0.598658  0.156019  0.155995
B 1  0.058084  0.866176  0.601115
  2  0.708073  0.020584  0.969910
C 1  0.832443  0.212339  0.181825
  2  0.183405  0.304242  0.524756

In [77]:
df.index.names = ['index1', 'index2']
df

                   col1      col2      col3
index1 index2
A      1       0.374540  0.950714  0.731994
       2       0.598658  0.156019  0.155995
B      1       0.058084  0.866176  0.601115
       2       0.708073  0.020584  0.969910
C      1       0.832443  0.212339  0.181825
       2       0.183405  0.304242  0.524756

In [ ]:
# 인덱스 이름 - 만들면서 알려주기

index_arr = [['A', 'A', 'B', 'B', 'C', 'C'], [1,2,1,2,1,2]]
index = pd.MultiIndex.from_arrays(index_arr, names= ('index1', 'index2'))
#                                            ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

df = pd.DataFrame(rng.rand(6,3), 
                  index=index,
                  columns= ['col1', 'col2', 'col3']
                  )

df

                   col1      col2      col3
index1 index2
A      1       0.431945  0.291229  0.611853
       2       0.139494  0.292145  0.366362
B      1       0.456070  0.785176  0.199674
       2       0.514234  0.592415  0.046450
C      1       0.607545  0.170524  0.065052
       2       0.948886  0.965632  0.808397

In [81]:
# 행만 있냐? 컬럼도 있다
row_index = pd.MultiIndex.from_product([[2013, 2014], ['1st', '2nd']], names = ['Year', 'Visit'])
col_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names= ['Patient', 'Data type'])
print(row_index)
print(col_index)

MultiIndex([(2013, '1st'),
            (2013, '2nd'),
            (2014, '1st'),
            (2014, '2nd')],
           names=['Year', 'Visit'])
MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['Patient', 'Data type'])

In [82]:
data_hr = np.random.randint(50, 80, 12) # 50부터 79까지의 정수중에서 무작위로 12개 선택
data_temp = 37 + np.random.randn(12) # 평균이 0이고 표준편차가 1인 표준정규분포 random number 12개

data_x = [i for i in zip(data_hr, data_temp)]
data_x

[(np.int32(78), np.float64(36.2922555427599)),
 (np.int32(62), np.float64(38.041867569170435)),
 (np.int32(56), np.float64(37.53006774732211)),
 (np.int32(63), np.float64(37.714607399141585)),
 (np.int32(70), np.float64(37.37345060660527)),
 (np.int32(52), np.float64(36.5410971370366)),
 (np.int32(74), np.float64(36.12242356159405)),
 (np.int32(67), np.float64(38.74456305599067)),
 (np.int32(65), np.float64(36.33796182315771)),
 (np.int32(59), np.float64(36.393205191921915)),
 (np.int32(68), np.float64(36.8331769333992)),
 (np.int32(68), np.float64(38.6629674131834))]

In [83]:
arr = np.array(data_x)
arr

array([[78.        , 36.29225554],
       [62.        , 38.04186757],
       [56.        , 37.53006775],
       [63.        , 37.7146074 ],
       [70.        , 37.37345061],
       [52.        , 36.54109714],
       [74.        , 36.12242356],
       [67.        , 38.74456306],
       [65.        , 36.33796182],
       [59.        , 36.39320519],
       [68.        , 36.83317693],
       [68.        , 38.66296741]])

In [84]:
# Reshape to 4 rows and 6 cols
arr_multi = arr.reshape(4,6)
arr_multi

array([[78.        , 36.29225554, 62.        , 38.04186757, 56.        ,
        37.53006775],
       [63.        , 37.7146074 , 70.        , 37.37345061, 52.        ,
        36.54109714],
       [74.        , 36.12242356, 67.        , 38.74456306, 65.        ,
        36.33796182],
       [59.        , 36.39320519, 68.        , 36.83317693, 68.        ,
        38.66296741]])

In [85]:
health_data = pd.DataFrame(arr_multi, columns=col_index, index=row_index)
health_data

Patient      Bob            Guido              Sue
Data type     HR       Temp    HR       Temp    HR       Temp
Year Visit
2013 1st    78.0  36.292256  62.0  38.041868  56.0  37.530068
     2nd    63.0  37.714607  70.0  37.373451  52.0  36.541097
2014 1st    74.0  36.122424  67.0  38.744563  65.0  36.337962
     2nd    59.0  36.393205  68.0  36.833177  68.0  38.662967

In [86]:
health_data['Bob']

Data type     HR       Temp
Year Visit
2013 1st    78.0  36.292256
     2nd    63.0  37.714607
2014 1st    74.0  36.122424
     2nd    59.0  36.393205

In [87]:
health_data['Bob']['HR']

Year  Visit
2013  1st      78.0
      2nd      63.0
2014  1st      74.0
      2nd      59.0
Name: HR, dtype: float64

In [ ]:
health_data.loc[2014, ('Bob','HR')]
# health_data.loc[2014, ['Bob','HR']]

# 튜플은 계층을 표현: ('Bob','HR') → 첫 번째 인덱스는 'Bob', 두 번째 인덱스는 'HR'
# 리스트는 단순 나열임 → 첫 번째 인덱스에 'Bob'은 있지만 'HR'는 없음

Visit
1st    74.0
2nd    59.0
Name: (Bob, HR), dtype: float64