# Pandas DataFrame 기초

## 📚 용어 정리 (Terminology)

### 기본 데이터 구조 용어

| 용어 (한글) | 용어 (영문) | 설명 | 시각적 표현 |
|------------|-----------|------|-----------|
| **행** | Row / Index | 가로 방향의 데이터 줄. 위에서 아래로 날아감. | → (가로) |
| **열** | Column | 세로 방향의 데이터 줄. 왼쪽에서 오른쪽으로 진행. | ↓ (세로) |
| **셀** | Cell | 행과 열이 교차하는 하나의 데이터 단위 | 사각형 한 칸 |
| **인덱스** | Index | 각 행을 고유하게 식별하는 레이블 (0, 1, 2, ...) | 행의 '이름' |
| **컬럼명** | Column Name | 각 열을 식별하는 이름 ('Name', 'Age', 등) | 열의 '이름' |

### pandas 핵심 용어

| 용어 | 정의 | 비유 |
|------|------|------|
| **Series** | 1차원 배열 (한 줄의 데이터) | Excel의 한 열(Column) |
| **DataFrame** | 2차원 테이블 (행+열 구조) | Excel의 전체 시트 |
| **dtype** | 데이터 타입 (int, float, object 등) | 변수의 자료형 |
| **NaN** | Not a Number (결측값) | 빈칸, NULL |
| **레이블** | Label | 인덱스나 컬럼의 이름 | 주소, 이름표 |

### 방향 관련 용어

```
     컬럼명 (Column) → 가로 (Horizontal)
          ↓
    ┌─────┬─────┬─────┐
인덱스 │  A  │  B  │  C  │
(Row)├─────┼─────┼─────┤
  ↓  │  1  │  2  │  3  │  ← 데이터 셀 (Cell)
세로  ├─────┼─────┼─────┤
(Vertical)│  4  │  5  │  6  │
    └─────┴─────┴─────┘
```

### 중요 구분
- **Axis 0**: 행(Row) 방향, 위→아래, `axis=0` 또는 `axis='index'`
- **Axis 1**: 열(Column) 방향, 왼쪽→오른쪽, `axis=1` 또는 `axis='columns'`

---

## 1. DataFrame 생성하기

**DataFrame**은 pandas에서 제공하는 2차원 테이블 형태의 데이터 구조입니다.
- 행(index)과 열(column)로 구성되어 있습니다
- 각 열은 서로 다른 데이터 타입을 가질 수 있습니다
- Excel의 스프레드시트나 SQL의 테이블과 유사한 구조입니다

### DataFrame을 만드는 다양한 방법:
1. 빈 DataFrame 생성
2. 리스트(list)로 생성
3. 딕셔너리(dictionary)로 생성
4. NumPy 배열로 생성

In [ ]:
# Dataframe 만들기

In [1]:
import pandas as pd

df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [27]:
import pandas as pd

lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

### DataFrame 기본 정보 확인

| 메서드 | 설명 |
|--------|------|
| `df.shape` | (행 수, 열 수) 튜플 반환 |
| `df.dtypes` | 각 열의 데이터 타입 확인 |
| `df.head(n)` | 상위 n개 행 출력 (기본 5개) |
| `df.tail(n)` | 하위 n개 행 출력 (기본 5개) |
| `df.info()` | DataFrame 전체 정보 요약 |

In [28]:
# df.shape: DataFrame의 크기를 (행, 열) 형태의 튜플로 반환
# 결과 (7, 1)은 7개의 행과 1개의 열이 있음을 의미
df.shape

(7, 1)

In [ ]:
# df.dtypes: 각 열의 데이터 타입을 Series 형태로 반환
# 결과 해석:
# - 컬럼 0의 타입은 object (문자열)
# - object는 pandas에서 문자열을 의미

df.dtypes

0    object
dtype: object

### Pandas 주요 데이터 타입

| 타입 | 설명 | 예시 |
|------|------|------|
| `int64` | 64비트 정수 | 1, 2, 3 |
| `float64` | 64비트 실수 | 1.5, 3.14 |
| `object` | 문자열 | 'hello', 'world' |
| `bool` | 불리언 | True, False |
| `datetime64` | 날짜/시간 | 2024-01-01 |
| `category` | 카테고리형 | 'A', 'B', 'C' |

In [30]:
# df.head(n): 상위 n개 행 출력 (기본값 n=5)
# 데이터의 앞부분을 미리보기할 때 유용
df.head()

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal

In [31]:
df.tail()

        0
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [32]:
df.head(3)

       0
0  Geeks
1    For
2  Geeks

In [33]:
df.tail(3)

        0
4  portal
5     for
6   Geeks

In [35]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## 2. Series와 DataFrame의 관계

**Series**는 1차원 배열로, DataFrame의 한 열(column)을 의미합니다.

- DataFrame은 여러 개의 Series가 모여 만든 2차원 테이블
- 각 Series는 고유한 index를 가짐
- 단일 열을 선택하면 Series 타입이 반환됨

In [37]:
# DataFrame에서 단일 열을 선택하면 Series 타입이 반환됨
# df['컬럼명'] 또는 df.컬럼명 으로 접근 가능

column_a = df['A']
print(f"'A' 컬럼의 타입: {type(column_a)}")

'A' 컬럼의 타입: <class 'pandas.core.series.Series'>

In [40]:
print(column_a)
print('-'*100)
print(column_a.index)
print('-'*100)
print(list(column_a.index))

0    1
1    4
2    7
Name: A, dtype: int64
----------------------------------------------------------------------------------------------------
RangeIndex(start=0, stop=3, step=1)
----------------------------------------------------------------------------------------------------
[0, 1, 2]

In [ ]:
df.dtypes
# 이 자체가 series
# df.dtypes를 요청하면 답을 Series 형태로 리턴한다는 의미


# A    int64
# B    int64
# C    int64
# 이 자체가 series가 되고 series의 값인 int64, int64, int64의 타입이 object라는 의미

A    int64
B    int64
C    int64
dtype: object

In [5]:
import pandas as pd

# initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [4]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

## 3. 인덱싱과 슬라이싱

### 📚 인덱싱 용어 정리

| 용어 | 정의 | 예시 | 비고 |
|------|------|------|------|
| **인덱싱 (Indexing)** | 특정 데이터를 선택하여 가져오는 것 | `df[0]`, `df['Name']` | 위치나 이름으로 선택 |
| **슬라이싱 (Slicing)** | 범위를 지정하여 여러 데이터를 선택 | `df[0:3]`, `df['A':'C']` | 시작:끝 형태 |
| **레이블 (Label)** | 인덱스나 컬럼의 이름 | `'Name'`, `0`, `'Alice'` | 문자열 또는 숫자 |
| **위치 (Position)** | 0부터 시작하는 정수 순서 | 0, 1, 2, 3... | Python은 0부터 시작 |
| **마스크 (Mask)** | True/False로 구성된 불리언 배열 | `[True, False, True]` | 필터링에 사용 |

### 🎯 loc vs iloc 상세 비교

| 구분 | `loc` | `iloc` |
|------|-------|--------|
| **의미** | location (레이블 기반) | integer location (정수 위치 기반) |
| **사용 값** | 인덱스 레이블 (이름) | 0부터 시작하는 정수 위치 |
| **슬라이싱** | 끝값 **포함** `[a:b]` → a, b 모두 포함 | 끝값 **미포함** `[a:b]` → a만 포함 |
| **사용 예** | `df.loc['Alice']` | `df.iloc[0]` |
| **특징** | 이름으로 찾기 | 순서(번호)로 찾기 |

```
DataFrame 예시:
             Name    Age   (컬럼 레이블)
          ┌────────┬──────┐
0 (인덱스) │ 'Alice'│  30  │  ← 첫 번째 행 (위치 0)
          ├────────┼──────┤
1 (인덱스) │  'Bob' │  25  │  ← 두 번째 행 (위치 1)
          └────────┴──────┘

loc[0] → 인덱스 레이블이 0인 행 선택
iloc[0] → 위치 0번째(첫 번째) 행 선택
```

### 인덱스(Index)란?
- DataFrame의 각 행을 고유하게 식별하는 레이블
- 기본적으로 0, 1, 2, ... 와 같은 정수 인덱스가 자동 생성됨
- 사용자가 원하는 값으로 인덱스를 설정할 수 있음 (set_index)

### 주요 인덱싱 방법

| 방법 | 설명 | 예시 |
|------|------|------|
| `df['컬럼명']` | 단일 열 선택 | `df['Name']` |
| `df[['컬럼1', '컬럼2']]` | 여러 열 선택 | `df[['Name', 'Age']]` |
| `df.loc[]` | 레이블 기반 인덱싱 | `df.loc[0, 'Name']` |
| `df.iloc[]` | 위치 기반 인덱싱 (정수) | `df.iloc[0, 0]` |
| `df.set_index()` | 특정 열을 인덱스로 설정 | `df.set_index('Name')` |
| `df.reset_index()` | 인덱스를 기본값으로 리셋 | `df.reset_index()` |

In [ ]:
# 인덱싱

In [47]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print(df.index)
# print(list(df.index))

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
RangeIndex(start=0, stop=5, step=1)

In [48]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [49]:
# Reset the index back to the default integer index
df_reset = df_with_index.reset_index()
print(df_reset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [50]:
# 한편 df_with_index는?
df_with_index

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [55]:
df_with_index.reset_index(inplace=True)
# inplace=True는 복사본을 만들지 않고 원본을 수정하라는 의미
df_with_index

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [56]:
# df_with_index = df.set_index('Name')

# 에러 발생
row = df_with_index.loc['Alice']
print(row)

KeyError: 'Alice'

In [57]:
df

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [ ]:
# loc을 사용하여 특정 행 선택
# df.loc[0]은 인덱스 레이블이 0인 행을 선택
# 결과의 'Name: 0'은 이 Series가 원본 DataFrame의 인덱스 0번에서 가져온 데이터임을 의미

df.loc[0]

Name       John
Age          25
Gender     Male
Salary    50000
Name: 0, dtype: object

In [59]:
# Set 'Age' as the new index
df_with_new_index = df.set_index('Age')
print(df_with_new_index)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

In [ ]:
# 인덱스의 타입은 dtype='int64'
df_with_new_index.index

Index([25, 30, 22, 35, 28], dtype='int64', name='Age')

In [ ]:
# 인덱스의 타입은 dtype='int64'이므로 "30"이 아니라 30

df_with_new_index.loc[30]
# df_with_new_index.loc["30"]

Name       Alice
Gender    Female
Salary     55000
Name: 30, dtype: object

In [79]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [80]:
# iloc은 위치 기반 인덱싱 (0부터 시작하는 정수)
# df.iloc[1]은 두 번째 행(인덱스 1)을 선택
# 주의: loc과 달리 인덱스 레이블이 아닌 위치(순서)를 기준으로 선택

second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [82]:
# df.loc[a:b]에서 b는 포함
# df.loc은 언제나 인덱스 레이블을 기준
print(df)
print("-"*100)
subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
----------------------------------------------------------------------------------------------------
    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [ ]:
# 마스크(Mask) 생성
# 조건식을 적용하면 각 행에 대해 True/False 값을 가진 Boolean Series(마스크)가 생성됨
# df['Age'] > 25는 Age 컬럼의 값이 25보다 큰지 검사

df['Age'] > 25

0    False
1     True
2    False
3     True
4     True
Name: Age, dtype: bool

### 📚 불리언 인덱싱 (Boolean Indexing) 용어 정리

| 용어 | 정의 | 예시 |
|------|------|------|
| **Boolean** | 참(True)/거짓(False) 두 값만 가지는 논리 타입 | `True`, `False` |
| **마스크 (Mask)** | 조건 결과에 따른 True/False 배열 | `[True, False, True]` |
| **필터링 (Filtering)** | 조건을 만족하는 데이터만 선택하는 것 | `df[df['Age'] > 20]` |
| **조건식** | 비교 연산을 포함한 식 | `df['Age'] > 25` |
| **논리 연산자** | 여러 조건을 결합하는 연산자 | `&` (AND), `|` (OR), `~` (NOT) |

### 비교 연산자 정리

| 연산자 | 의미 | 예시 | 결과 |
|--------|------|------|------|
| `>` | 크다 (greater than) | `5 > 3` | True |
| `<` | 작다 (less than) | `5 < 3` | False |
| `==` | 같다 (equal to) | `5 == 5` | True |
| `!=` | 같지 않다 (not equal) | `5 != 3` | True |
| `>=` | 크거나 같다 | `5 >= 5` | True |
| `<=` | 작거나 같다 | `3 <= 5` | True |

### 논리 연산자 정리 (주의: 괄호 필수!)

| 연산자 | 의미 | 설명 | 예시 |
|--------|------|------|------|
| `&` | AND (그리고) | 두 조건 모두 참이어야 True | `(df['Age'] > 20) & (df['Age'] < 30)` |
| `|` | OR (또는) | 둘 중 하나만 참이어도 True | `(df['Age'] < 20) | (df['Age'] > 60)` |
| `~` | NOT (부정) | True를 False로, False를 True로 | `~(df['Age'] > 20)` |

```python
# ⚠️ 중요: 각 조건은 반드시 괄호로 묶어야 함!
# 틀림: df['Age'] > 20 & df['Age'] < 30
# 맞음: (df['Age'] > 20) & (df['Age'] < 30)
```

### 불리언 인덱싱 과정

```
Step 1: 조건식 적용 → 마스크 생성
  df['Age'] > 25
  [25, 30, 22, 35] > 25
  → [False, True, False, True]  (마스크)

Step 2: 마스크를 DataFrame에 적용
  df[마스크]
  → True인 행만 선택됨
```

In [ ]:
# 불리언 인덱싱: Age가 25보다 큰 행들만 필터링
# 마스크를 DataFrame에 적용하여 True인 행만 선택

filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [83]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [87]:
# loc[j:k]와 iloc[j:k]의 차이는 k가 포함되고 안되고
df1 = df.iloc[0:4]
print(df1)

print('-'*100)

# df.loc은 언제나 인덱스 레이블을 기준
print(list(df.index))

print('-'*100)

df2 = df.loc[0:4]
print(df2)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
----------------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4, 5, 6]
----------------------------------------------------------------------------------------------------
            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000

In [71]:
df1 = df.iloc[:, 0:2]

print(df1)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [89]:
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [90]:
# iloc[a, b]에서 a는 행, b는 열의 위치를 선택
value = df.iloc[2, 3]  
print(value)

8428000

In [91]:
df

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [92]:
df.set_index('Name', inplace=True)
df

               Age  Weight   Salary
Name
M.S.Dhoni       36      75  5428000
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000
J.Root          33      72  7028000
K.Peterson      42      85  2528000

In [ ]:
# loc으로 특정 값 선택하기
# df.loc은 언제나 인덱스 레이블을 기준

value = df.loc['V.Kohli', 'Salary']
print(value)

8428000

In [2]:
import pandas as pd

# 샘플 데이터 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Seoul'],
    'Score': [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data, index=['p1', 'p2', 'p3', 'p4', 'p5'])

df

       Name  Age      City  Score
p1    Alice   25  New York     85
p2      Bob   30    London     92
p3  Charlie   35     Paris     78
p4    David   40     Tokyo     95
p5      Eve   45     Seoul     88

In [ ]:
# 인덱스 이름(레이블)이 p2인 사람의 'City' 정보를 가져오려면? .loc를 사용하여 코드를 한 줄로 작성

'London'

In [ ]:
# 데이터프레임의 첫 번째 행부터 세 번째 행까지만 선택하려면? .iloc를 사용하여 코드를 한 줄로 작성

       Name  Age      City  Score
p1    Alice   25  New York     85
p2      Bob   30    London     92
p3  Charlie   35     Paris     78

In [ ]:
# Score가 90점 이상인 데이터들만 필터링하여 전체 컬럼을 출력하려면?

     Name  Age    City  Score
p2    Bob   30  London     92
p4  David   40   Tokyo     95

In [ ]:
# 나이가 35세 이상인 사람들의 Name과 Score 컬럼을 출력하려면?

       Name  Score
p3  Charlie     78
p4    David     95
p5      Eve     88

In [ ]:

# df.loc['p2', 'City']
# df.iloc[0:3]
# df[df['Score'] >= 90]
# df[df['Age'] >= 35][['Name', 'Score']]